"""Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms."""


def even_last_number(func):
    limit = 4000000
    numbers = [0]
    for num in range(limit):
        result = func(num)
        if result % 2 == 0:
            numbers.append(result)
            if result > limit:
                numbers = numbers[:-1]
                break
    return sum(numbers)


@even_last_number
def fib(n):
    a, b = 0, 1
    for num in range(n):
        a, b = b, a + b
    return a

print(fib)
